application: partyplannrcom
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico
  
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
  
- url: /xd_receiver.htm
  static_files: xd_receiver.htm
  upload: xd_receiver.htm
  
- url: /session
  static_files: session
  upload: session
  
- url: /assets
  static_dir: assets
  
- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js

- url: /.*
  script: partyplannr.py
  
  